language: rust
addons:
  apt:
    packages:
      - libopenblas-dev
      - gfortran
sudo: required
rust:
  - 1.32.0
  - stable
before_script:
  - rustup component add clippy
  - rustup component add rustfmt
script: ci/script.sh
dist: trusty